"""Batch generation must preserve existing files unless --clobber is supplied.

> NOTE: not reviewed in detail.
"""

import json
import os
import tempfile
import unittest
from io import StringIO
from pathlib import Path
from unittest.mock import patch

from program_ssa import format_program, main, parse_program
from tests.test_program_ssa import scalar_program


class RegenerationTests(unittest.TestCase):
    def setUp(self) -> None:
        Path(".context").mkdir(exist_ok=True)
        temporary = tempfile.TemporaryDirectory(dir=".context")
        self.addCleanup(temporary.cleanup)
        self.directory = Path(temporary.name)
        self.first = self.directory / "json" / "a.json"
        self.last = self.directory / "json" / "nested" / "z.json"
        self.last.parent.mkdir(parents=True)
        self.outputs = {
            self.first: self.directory / "ssa" / "a.ssa",
            self.last: self.directory / "ssa" / "nested" / "z.ssa",
        }
        self.program = scalar_program()
        self.generated = format_program(self.program).encode("utf-8")
        for path in (self.first, self.last):
            path.write_text(json.dumps(self.program), encoding="utf-8")

    def run_command(self, *flags: str) -> tuple[int, str, str]:
        stdout, stderr = StringIO(), StringIO()
        with patch("sys.stdout", stdout), patch("sys.stderr", stderr):
            status = main(["json2ssa", "all", "--programs-root", str(self.directory), *flags])
        return status, stdout.getvalue(), stderr.getvalue()

    def write_existing(self, path: Path, content: bytes) -> Path:
        output = self.outputs[path]
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(content)
        return output

    def test_clobber_creates_missing_companions_recursively(self) -> None:
        status, output, error = self.run_command("--clobber")
        self.assertEqual(status, 0, error)
        self.assertIn("Wrote 2", output)
        for path in (self.first, self.last):
            ssa_path = self.outputs[path]
            self.assertEqual(ssa_path.read_bytes(), self.generated)
            self.assertEqual(parse_program(ssa_path.read_text(encoding="utf-8")), self.program)
        self.assertFalse(list((self.directory / "json").rglob("*.ssa")))

    def test_matching_files_are_not_rewritten(self) -> None:
        for path in (self.first, self.last):
            output = self.write_existing(path, self.generated)
            os.utime(output, ns=(1_000_000_000, 1_000_000_000))
        for flags in ((), ("--clobber",)):
            with self.subTest(flags=flags):
                status, output, error = self.run_command(*flags)
                self.assertEqual(status, 0, error)
                self.assertIn("Wrote 0 SSA file(s); 2 already up to date", output)
                for path in (self.first, self.last):
                    self.assertEqual(self.outputs[path].stat().st_mtime_ns, 1_000_000_000)

    def test_matching_file_does_not_hide_missing_companions(self) -> None:
        self.write_existing(self.first, self.generated)
        status, output, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertEqual(output, "")
        self.assertIn(str(self.outputs[self.last]), error)
        self.assertIn("is missing", error)
        self.assertIn("--clobber", error)
        self.assertFalse(self.outputs[self.last].exists())
        status, output, error = self.run_command("--clobber")
        self.assertEqual(status, 0, error)
        self.assertIn("Wrote 1 SSA file(s); 1 already up to date", output)
        self.assertEqual(self.outputs[self.last].read_bytes(), self.generated)

    def test_initial_generation_requires_clobber(self) -> None:
        status, output, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertEqual(output, "")
        self.assertIn("is missing", error)
        self.assertFalse((self.directory / "ssa").exists())

    def test_missing_companion_aborts_without_changing_existing_files(self) -> None:
        # Even semantically equivalent SSA differs from canonical generated bytes.
        modified = b"# handwritten comment\n" + self.generated
        output = self.write_existing(self.last, modified)
        status, stdout, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertEqual(stdout, "")
        self.assertIn(str(self.outputs[self.first]), error)
        self.assertIn("is missing", error)
        self.assertIn("--clobber", error)
        self.assertEqual(output.read_bytes(), modified)
        self.assertFalse(self.outputs[self.first].exists())

    def test_matching_file_does_not_hide_a_later_mismatch(self) -> None:
        self.write_existing(self.first, self.generated)
        self.write_existing(self.last, b"stale")
        status, _, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertIn("differs from generated SSA", error)
        self.assertEqual(self.outputs[self.last].read_text(), "stale")

    def test_clobber_overwrites_mismatches_and_creates_missing_files(self) -> None:
        self.write_existing(self.last, b"stale")
        status, output, error = self.run_command("--clobber")
        self.assertEqual(status, 0, error)
        self.assertIn("Wrote 2", output)
        for path in (self.first, self.last):
            self.assertEqual(self.outputs[path].read_bytes(), self.generated)

    def test_clobber_replaces_changed_files_when_all_companions_exist(self) -> None:
        self.write_existing(self.first, self.generated)
        output = self.write_existing(self.last, b"# added comment\n" + self.generated)
        status, _, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertIn("differs from generated SSA", error)
        status, stdout, error = self.run_command("--clobber")
        self.assertEqual(status, 0, error)
        self.assertIn("Wrote 1 SSA file(s); 1 already up to date", stdout)
        self.assertEqual(output.read_bytes(), self.generated)

    def test_unaccounted_files_block_generation_even_with_clobber(self) -> None:
        existing = self.write_existing(self.first, b"stale")
        for relative in ("orphan.ssa", "nested/a.ssa", "notes.txt"):
            orphan = self.directory / "ssa" / relative
            orphan.parent.mkdir(parents=True, exist_ok=True)
            orphan.write_text("unaccounted", encoding="utf-8")
            for flags in ((), ("--clobber",)):
                with self.subTest(orphan=relative, flags=flags):
                    status, stdout, error = self.run_command(*flags)
                    self.assertEqual(status, 1)
                    self.assertEqual(stdout, "")
                    self.assertIn("unaccounted files without matching JSON", error)
                    self.assertIn(str(orphan), error)
                    self.assertEqual(orphan.read_text(), "unaccounted")
                    self.assertEqual(existing.read_bytes(), b"stale")
                    self.assertFalse(self.outputs[self.last].exists())
            orphan.unlink()

    def test_deleted_json_leaves_an_orphan_that_clobber_cannot_hide(self) -> None:
        for path in (self.first, self.last):
            self.write_existing(path, self.generated)
            path.unlink()
        for flags in ((), ("--clobber",)):
            with self.subTest(flags=flags):
                status, _, error = self.run_command(*flags)
                self.assertEqual(status, 1)
                self.assertIn("unaccounted files without matching JSON", error)
                for output in self.outputs.values():
                    self.assertIn(str(output), error)
                    self.assertEqual(output.read_bytes(), self.generated)

    def test_invalid_json_prevents_all_writes_even_with_clobber(self) -> None:
        self.last.write_text("invalid JSON", encoding="utf-8")
        output = self.write_existing(self.first, b"keep me")
        status, _, error = self.run_command("--clobber")
        self.assertEqual(status, 1)
        self.assertIn(str(self.last), error)
        self.assertEqual(output.read_text(), "keep me")
        self.assertFalse(self.outputs[self.last].exists())

    def test_preflight_failure_does_not_create_output_directories(self) -> None:
        self.last.write_text("invalid JSON", encoding="utf-8")
        status, _, error = self.run_command("--clobber")
        self.assertEqual(status, 1)
        self.assertIn(str(self.last), error)
        self.assertFalse((self.directory / "ssa").exists())

    def test_comparison_includes_line_endings(self) -> None:
        self.write_existing(self.first, self.generated.replace(b"\n", b"\r\n"))
        status, _, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertIn("differs from generated SSA", error)

    def test_missing_or_empty_directory_is_an_error(self) -> None:
        for name in ("missing", "empty"):
            directory = self.directory / name
            if name == "empty":
                (directory / "json").mkdir(parents=True)
            with self.subTest(name=name), patch("sys.stderr", StringIO()) as error:
                self.assertEqual(main(["json2ssa", "all", "--programs-root", str(directory)]), 1)
                self.assertIn(str(directory), error.getvalue())

    def test_default_directory_is_programs(self) -> None:
        with patch("program_ssa.regenerate_programs", return_value=(0, 29)) as regenerate, patch("sys.stdout", StringIO()):
            self.assertEqual(main(["json2ssa", "all"]), 0)
        regenerate.assert_called_once_with(Path("programs"), clobber=False)

    def test_all_rejects_single_file_output(self) -> None:
        output = self.directory / "unexpected.ssa"
        with patch("sys.stderr", StringIO()) as error:
            self.assertEqual(main(["json2ssa", "all", "-o", str(output)]), 1)
        self.assertIn("single-file", error.getvalue())
        self.assertFalse(output.exists())


if __name__ == "__main__":
    unittest.main()
