"""Batch generation must preserve existing files unless --clobber is supplied."""

import json
import os
import tempfile
import unittest
from io import StringIO
from pathlib import Path
from unittest.mock import patch

from program_ssa import format_program, main, parse_program
from tests.test_program_ssa import scalar_program


class RegenerationTests(unittest.TestCase):
    def setUp(self) -> None:
        Path(".context").mkdir(exist_ok=True)
        temporary = tempfile.TemporaryDirectory(dir=".context")
        self.addCleanup(temporary.cleanup)
        self.directory = Path(temporary.name)
        self.first = self.directory / "a.json"
        self.last = self.directory / "nested" / "z.json"
        self.last.parent.mkdir()
        self.program = scalar_program()
        self.generated = format_program(self.program).encode("utf-8")
        for path in (self.first, self.last):
            path.write_text(json.dumps(self.program), encoding="utf-8")

    def run_command(self, *flags: str) -> tuple[int, str, str]:
        stdout, stderr = StringIO(), StringIO()
        with patch("sys.stdout", stdout), patch("sys.stderr", stderr):
            status = main(["regenerate", str(self.directory), *flags])
        return status, stdout.getvalue(), stderr.getvalue()

    def test_creates_missing_companions_recursively(self) -> None:
        status, output, error = self.run_command()
        self.assertEqual(status, 0, error)
        self.assertIn("Wrote 2", output)
        for path in (self.first, self.last):
            ssa_path = path.with_suffix(".ssa")
            self.assertEqual(ssa_path.read_bytes(), self.generated)
            self.assertEqual(parse_program(ssa_path.read_text(encoding="utf-8")), self.program)

    def test_matching_files_are_not_rewritten(self) -> None:
        for path in (self.first, self.last):
            output = path.with_suffix(".ssa")
            output.write_bytes(self.generated)
            os.utime(output, ns=(1_000_000_000, 1_000_000_000))
        for flags in ((), ("--clobber",)):
            with self.subTest(flags=flags):
                status, output, error = self.run_command(*flags)
                self.assertEqual(status, 0, error)
                self.assertIn("Wrote 0 SSA file(s); 2 already up to date", output)
                for path in (self.first, self.last):
                    self.assertEqual(path.with_suffix(".ssa").stat().st_mtime_ns, 1_000_000_000)

    def test_matching_file_does_not_hide_missing_companions(self) -> None:
        self.first.with_suffix(".ssa").write_bytes(self.generated)
        status, output, error = self.run_command()
        self.assertEqual(status, 0, error)
        self.assertIn("Wrote 1 SSA file(s); 1 already up to date", output)
        self.assertEqual(self.last.with_suffix(".ssa").read_bytes(), self.generated)

    def test_mismatch_aborts_before_creating_missing_companions(self) -> None:
        output = self.last.with_suffix(".ssa")
        # Even semantically equivalent SSA differs from canonical generated bytes.
        modified = b"# handwritten comment\n" + self.generated
        output.write_bytes(modified)
        status, stdout, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertEqual(stdout, "")
        self.assertIn(str(output), error)
        self.assertIn("--clobber", error)
        self.assertEqual(output.read_bytes(), modified)
        self.assertFalse(self.first.with_suffix(".ssa").exists())

    def test_matching_file_does_not_hide_a_later_mismatch(self) -> None:
        self.first.with_suffix(".ssa").write_bytes(self.generated)
        self.last.with_suffix(".ssa").write_text("stale", encoding="utf-8")
        status, _, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertIn("differs from generated SSA", error)
        self.assertEqual(self.last.with_suffix(".ssa").read_text(), "stale")

    def test_clobber_overwrites_mismatches_and_creates_missing_files(self) -> None:
        self.last.with_suffix(".ssa").write_text("stale", encoding="utf-8")
        status, output, error = self.run_command("--clobber")
        self.assertEqual(status, 0, error)
        self.assertIn("Wrote 2", output)
        for path in (self.first, self.last):
            self.assertEqual(path.with_suffix(".ssa").read_bytes(), self.generated)

    def test_invalid_json_prevents_all_writes_even_with_clobber(self) -> None:
        self.last.write_text("invalid JSON", encoding="utf-8")
        output = self.first.with_suffix(".ssa")
        output.write_text("keep me", encoding="utf-8")
        status, _, error = self.run_command("--clobber")
        self.assertEqual(status, 1)
        self.assertIn(str(self.last), error)
        self.assertEqual(output.read_text(), "keep me")
        self.assertFalse(self.last.with_suffix(".ssa").exists())

    def test_comparison_includes_line_endings(self) -> None:
        output = self.first.with_suffix(".ssa")
        output.write_bytes(self.generated.replace(b"\n", b"\r\n"))
        status, _, error = self.run_command()
        self.assertEqual(status, 1)
        self.assertIn("differs from generated SSA", error)

    def test_missing_or_empty_directory_is_an_error(self) -> None:
        for name in ("missing", "empty"):
            directory = self.directory / name
            if name == "empty":
                directory.mkdir()
            with self.subTest(name=name), patch("sys.stderr", StringIO()) as error:
                self.assertEqual(main(["regenerate", str(directory)]), 1)
                self.assertIn(str(directory), error.getvalue())

    def test_default_directory_is_programs(self) -> None:
        with patch("program_ssa.regenerate_programs", return_value=(0, 29)) as regenerate, patch("sys.stdout", StringIO()):
            self.assertEqual(main(["regenerate"]), 0)
        regenerate.assert_called_once_with(Path("programs"), clobber=False)


if __name__ == "__main__":
    unittest.main()
